### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by bakermiles** [aayushsh06/Brainrot-to-AI#1]
Everything is installed and double checked. cant seem to figure this issue out. To my knowledge I've set everything up correctly.

 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 102-379-099
127.0.0.1 - - [16/Dec/2024 04:25:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Dec/2024 04:25:18] "POST /process HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Miles\VideoAI\app.py", line 24, in process
    subprocess.run(['python3', 'createVid.py'], check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1548, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by aayushsh06** [comment]
Try the following steps and let me know if they fix anything: 
- Check the python version that you have installed is working and correct using `python --version` and `python3 --version`.  If python3 is not recognized, it means that the executable name does not exist on your system. Try running `python genTTS.py`, then `python makeCaption.py`, then `python combine.py`.
* Note for this test you will need to have a video file inputted in line 5 of `combine.py`. 

If a video is generated then that means the issue is solely due to python3 not being recognized and you may need to reinstall to see if that helps. Let me know if the problem still persists.

**Comment by bakermiles** [comment]
TTS works but once I start makeCaption I get this error.

Traceback (most recent call last):
  File "C:\Users\Miles\VideoAI/Makecaption.py", line 8, in <module>
    import whisper
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Users\Miles\AppData\Local\Programs\Python\Python313\Lib\ctypes\__init__.py", line 380, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by aayushsh06** [comment]
Try running the following in your terminal: `pip install openai-whisper`. It seems this dependency was missed in the requirements file.
